### ISSUE TITLE
VillageGenerator.cs /house command error

### ISSUE THREAD

**Issue by jchappelle** [anegostudios/vsmodexamples#2]
I get the following error when running the VillageGenerator.cs and typing /house to generate the house. If I had to guess I would say the following code is using an invalid npc identifier.

`api.AddNpc("Jeniffer", pos.UpCopy());`

```
2/13/2017 5:01:18 PM: Critical error occurred
System.Exception: Don't know how to instantiate entity of type playernpc did you forget to register a mapping?
   at _Jr2ChpGEe4EhkP2shcnBoYgQ8UP._1zWAH1LHEdyCQK9ZwQsStkHglEl(String )
   at _3xH9Bn8wn1Sp3II82nuKkHhrGtb._6vr6kJKi59RF68lkanGnm4y9DlJ(_FU4kDDeSa8qwnY2SqnAeRiVMuLO , _Iv9jE84AXlIpk9ZNk5dozZ5VbJK )
   at _3xH9Bn8wn1Sp3II82nuKkHhrGtb._sj4UPzTJJuW4bN8Iwi1Lcqmpe1A(_RWNzQ6wFDPtlJwNaw9UwmWbxzQb )
   at _WdUXfBjAw07E9HD4XTY2qZM4Hin._Ep1OR78qfn6d6vWHqd0N5lOdLdP(_Iv9jE84AXlIpk9ZNk5dozZ5VbJK , Single )
   at _Iv9jE84AXlIpk9ZNk5dozZ5VbJK._xYsANJZcrzhfNyC92lZTwlH2QeaA(Single )
   at _VMVAbig8IeaOvC5T8vQR0FuJtz._yksiHFni7U9rXbSKDctalZUuUUb(Single )
   at _VMVAbig8IeaOvC5T8vQR0FuJtz._eKhWiKnR7qrpd5aQvm2hkNNs5TD(Single )
   at _mpCvOleoPKUlA5HCPjSCdQLbZvU._xNHhO4GentNbm4IBBXDD8Ol75hv(Object , FrameEventArgs )
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchUpdateAndRenderFrame(Object sender, EventArgs e)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _5nMEWVHZ4jrGpFqyrkcrD0yJ4fc._XdAocWaUzQkcgVQeIEfdt5n2ZGN(String[] )
   at _EPJBes9AwwFLi4FHFqZJEHWnkK5._XdAocWaUzQkcgVQeIEfdt5n2ZGN(ThreadStart )
   at _5nMEWVHZ4jrGpFqyrkcrD0yJ4fc._8oZw14e19ftWBQUmZSdajfKfnQ6(String[] )
```

**Comment by tyronx** [comment]
Thanks should be fixed for next version
